name: Practice example-1
on: push

jobs:
  TestingPractise-1:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Testing the project
        run: npm test
           
      - name: Linting the project
        uses: wearerequired/lint-action@v2

      - name: Building
        run: npm run build
  Deploying:
    needs: TestingPractise-1
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying...."
      